sylius_twig_hooks:
    hooks:
        'sylius_admin.common.update':
            monsieurbiz.sylius_advanced_option_plugin.theme:
                template: "@MonsieurBizSyliusAdvancedOptionPlugin/Form/theme.html.twig"
                priority: 999
